### ISSUE TITLE
Strange behavior in the filter of the Excluded users list

### ISSUE THREAD

**Issue by headcase-fo** [ameyer505/D365FOAdminToolkit#25]
Hey @ameyer505,

thanks again for this great extension. We just deployed v1.5 and I tried the Excluded user list and stumbled upon some unexpected behavior.

Opening the filter in table User list at column User Id it already contains "is exactly" with the first user inserted, but the string looks like it is escaped somehow, e.g. "head.case" is displayed as "head.\case". 

Next step was changing the filter to "contains", adding "svc" as string but this did not work either. I had to empty the filter and try again a second time to get it working somehow. 

Another issue:
When trying to remove one or more entries from the excluded user list, at least one record of the user list is marked by default. While the others will be removed, this one will be added. That means you will never get an empty excluded user list again.

**Comment by jofme** [comment]
@ameyer505 @headcase-fo  I'll have a quick look at it (-:

**Comment by jofme** [comment]
@ameyer505 @headcase-fo Reproduced and fixed. It's no longer creating filters automatically.

I applied the pattern "Task Double" to the form, the design has changed a little. Hope it's okay

![image](https://github.com/ameyer505/D365FOAdminToolkit/assets/96665013/31530f93-5139-4fda-8d31-9d7c9a8941c5)
