### ISSUE TITLE
Error during Disable User Job

### ISSUE THREAD

**Issue by eatufano** [ameyer505/D365FOAdminToolkit#27]
Hi all,
I got sql error below during Disable Users Job (with 30 days as param).
Can you help me to better understand the reason?
Many thanks!

_UPDATE USERINFO SET ENABLE=?,RECVERSION=? WHERE (((PARTITION=?) AND (ID=?)) AND (RECVERSION=?))
[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]PowerPlatformApp user cannot be disabled!
Object Server Azure:
Cannot edit a record in User Information (UserInfo). User Information: 101090. The SQL database has issued an error._

**Comment by jofme** [comment]
Hi @eatufano

It looks like the job is trying to disable a service account.
Are you using the latest version of the toolkit? if yes can you check if the user is in this form:

![image](https://github.com/ameyer505/D365FOAdminToolkit/assets/96665013/bc4edb5b-2b02-49ba-bc30-f720be251c2b)

**Comment by ameyer505** [comment]
To add onto what @jofme said, there is a 'Populate Excluded Users' button which will add the default service accounts to the 'Excluded Users' list automatically. The PowerPlatformApp user is a part of this list.

![image](https://github.com/ameyer505/D365FOAdminToolkit/assets/3227457/4dc57413-90bb-4ccd-9305-9c58004457d2)
