### ISSUE TITLE
Canny request: Integrate D365FO telemetery data with SysAdmin assignment data

### ISSUE THREAD

**Issue by jofme** [ameyer505/D365FOAdminToolkit#33]
_Type: Enhancement_

**Add telemetry event on SysAdmin role assignment**
**Rough estimate**: 3 hours worth of development and testing

**Create new ADM parameter**: Track SysAdmin role assignments
**Use SysApplicationInsightsTelemetryLogger**: Example from standard application

```
    /// <summary>
    /// Log queries over 100ms to AppInsights.
    /// </summary>
    /// <param name = "_sqlStatement">The SQL statement executed.</param>
    /// <param name = "_executionTimeSec">The time the statement took in seconds.</param>
    /// <param name = "_queryType">The type of operation performed such as select, update, delete.</param>
    /// <param name = "_success">True if the query succeeded, false if an error occurred.</param>
    /// <param name = "_returnedRowCount">The number of rows returned from the statement.</param>
    /// <param name = "_joinCount">The number of joins in the statement.</param>
    internal static void longRunningQuery(str _sqlStatement, real _executionTimeSec, str _queryType, boolean _success, int64 _returnedRowCount, int _joinCount)
    {
        if(SysIntParameters::Find().CaptureLongQueries)
        {
            container callstackWithCaller = xSession::xppCallStackWithCaller();
            
            SysApplicationInsightsEventTelemetry eventTelemetry = SysApplicationInsightsEventTelemetry::newFromEventIdName('SQL00001', 'LongRunningQuery');
            eventTelemetry.addProperty(SysApplicationInsightsClassNameProperty::newFromValue(conPeek(callStackWithCaller, 1)));
            eventTelemetry.addProperty(SysApplicationInsightsMethodNameProperty::newFromValue(conPeek(callStackWithCaller, 2)));
            eventTelemetry.addProperty(SysApplicationInsightsCallStackProperty::newFromCallStackContainer(callstackWithCaller));
            eventTelemetry.addProperty(SysApplicationInsightsSqlQueryStatementProperty::newFromValue(_sqlStatement));
            eventTelemetry.addProperty(SysApplicationInsightsSqlQueryExecutionTimeSecondsProperty::newFromValue(any2Str(_executionTimeSec)));
            eventTelemetry.addProperty(SysApplicationInsightsSqlQueryTypeProperty::newFromValue(_queryType));
            eventTelemetry.addProperty(SysApplicationInsightsSqlQuerySuccessProperty::newFromValue(any2Str(_success)));
            eventTelemetry.addProperty(SysApplicationInsightsSqlQueryReturnedRowCountProperty::newFromValue(int642Str(_returnedRowCount)));
            eventTelemetry.addProperty(SysApplicationInsightsSqlQueryJoinCountProperty::newFromValue(int2Str(_joinCount)));

            SysApplicationInsightsTelemetryLogger::instance().trackEvent(eventTelemetry);
        }
    }
```

**Two types of events:**

- ADMSysAdminAssigned
- ADMSysAdminRemoved

**Event properties:**

- UserId
- Reason
- EndDate

**Comment by jofme** [comment]
I assume we can use the key ATK000001..... ?
Cannot remember the reason for the key format, but I don't want to conflict with the standard or break any telemetry parsing. ATK = AdminToolKit

These are the WHS keys
```
    internal static const str LocationDirectiveFindLocation = 'WHS000001';
    internal static const str WaveProcessingPostWave = 'WHS000002';
    internal static const str MobileAppNextPageRequest = 'WHS000003';
    internal static const str MobileAppImageRequest = 'WHS000004';
    internal static const str WorkCreationLog = 'WHS000005';
    internal static const str MobileAppRoundTrip = 'WHS000006'; // Used in the WMA repo, to log device-related telemetry when WMA receives a server response.
    internal static const str WaveProcessingCreateWork = 'WHS000007';
    internal static const str WaveProcessingCreateLoads = 'WHS000008';
    internal static const str WaveProcessingProcessWaveMethods = 'WHS000009';
    internal static const str WaveProcessingValidateWave = 'WHS000010';
    internal static const str WaveProcessingAllocateWave = 'WHS000011';
    internal static const str WaveProcessingContainerization = 'WHS000012';
    internal static const str LoadPosting = 'WHS000013';
    internal static const str WaveProcessingWaveDemandReplenishment = 'WHS000014';
    internal static const str WaveProcessingKanbanCreateWork = 'WHS000015';
    internal static const str WaveProcessingKanbanPickQuantity = 'WHS000016';
    internal static const str WaveProcessingProductionCreateWork = 'WHS000017';
    internal static const str WaveProcessingProductionPickQuantity = 'WHS000018';
    internal static const str WaveProcessingSorting = 'WHS000019';
    internal static const str WaveProcessingWaveLabelPrinting = 'WHS000020';
    internal static const str WaveProcessingCreateLoadFromShipment = 'WHS000021';
    internal static const str WorkCreationProcessTemporaryWorkLine = 'WHS000022';
    internal static const str WorkCreationCreateRemainingWorkLines = 'WHS000023';
    internal static const str LoadLineAllocationAllocateLoadLine = 'WHS000024';
    internal static const str RunDemandReplenishment = 'WHS000025';
    internal static const str ImmediateReplenishment = 'WHS000026';
    internal static const str WarehouseReleaseCreateShipments = 'WHS000027';
    internal static const str WaveCreated = 'WHS000028';
    internal static const str WaveStatusChanged = 'WHS000029';
```

**Comment by ameyer505** [comment]
@jofme - This is a great idea, I actually have a blog post on utilizing custom metrics / telemetry that we can utilize as a starting point: https://alexdmeyer.com/2023/10/03/using-telemetry-data-for-read-auditing-in-d365fo/

I do have to be slightly careful about my involvement in any telemetry data functionality as this an area that Delinea/Fastpath (my employer) is looking to expand their solution into.

**Comment by jofme** [comment]
> @jofme - This is a great idea, I actually have a blog post on utilizing custom metrics / telemetry that we can utilize as a starting point: https://alexdmeyer.com/2023/10/03/using-telemetry-data-for-read-auditing-in-d365fo/
> 


@ameyer505 That's awesome! There is not a lot of documentation out there on telemetry.

It looks like Microsoft deprecated SysGlobalTelemetry, at least in 10.0.40. But the framework should still work.
```
/// <summary>
/// Class used to log telemetry events to Application Insights in Azure
/// </summary>
[SysObsolete("SysGlobalTelemetry is obsolete. The SysApplicationInsightsGlobalTelemetry class is taking over the subscription methods. Client responsibilities are handled by SysApplicationInsightsTelemetryClientFactory and builder.", false, 01\12\2023)]
public class SysGlobalTelemetry

*SNIPPED*
```

> I do have to be slightly careful about my involvement in any telemetry data functionality as this an area that Delinea/Fastpath (my employer) is looking to expand their solution into.

Okay, no worries. We can also park the issue until Delinea/Fastpath has looked into telemetry?

**Comment by ameyer505** [comment]
@jofme - good call out on SysGlobalTelemetry being deprecated, I guess need to write an update to my blog post :)

Definitely think adding telemetry data to the D365FO Admin Toolkit is valuable, happy to continue to pursue it. If we get close to anything we are currently developing internally, I can just abstain my involvement

**Comment by jofme** [comment]
Thanks! I'm looking forward to it (-:
Check; I'll keep it in mind if I see other suggestions involving telemetry

**Comment by jofme** [comment]
@ameyer505 I have created a solution that does not create a conflict of interest. It works on the SysAdmin log table.
It uses the new framework for sending telemetry events. If you want to follow the standard pattern, it requires some additional classes.

The new framework requires this feature to be enabled:
![image](https://github.com/ameyer505/D365FOAdminToolkit/assets/96665013/c220f0f4-7d9e-4dee-8936-8da756f6fb33)

There is no good way to check if the feature is enabled and thereby revert to the old framework since it's all internal. I'm not able to create extensibility requests at the moment, but if you have time, please create one for this (-:
![image](https://github.com/ameyer505/D365FOAdminToolkit/assets/96665013/4784de52-ed7d-40d7-856e-5762b949cbe3)

I have created this parameter:
![image](https://github.com/ameyer505/D365FOAdminToolkit/assets/96665013/9ccacce7-3c22-4144-94bc-60c5ef1dc667)

The telemetry events will look like this in Application Insights:
 
![image](https://github.com/ameyer505/D365FOAdminToolkit/assets/96665013/580dc8a8-2503-4da3-80c3-2841b088c4f2)
