### ISSUE TITLE
Needed Roles documentation / naming

### ISSUE THREAD

**Issue by TrustCompact** [ameyer505/D365FOAdminToolkit#4]
[Here](https://alexdmeyer.com/2023/11/29/how-to-test-role-access-without-a-test-account-in-d365fo/) its written:

Note: The ‘Alex Meyer Security Toolkit’ role must be assigned to your user otherwise you will be unable to assign the SysAdmin role back to this user after your testing

Perhaps a note in the pdf-documentation would be helpful, too.
Also the role-names seems to have changed from "Alex Meyer Security Toolkit" to "D365FO Admin Toolkit Maintain" / ".../View"

Thanks for your effort and your work!

**Comment by ameyer505** [comment]
I have updated the documentation to include the new naming, the updated version can be found here: https://github.com/ameyer505/D365FOAdminToolkit/blob/main/D365FO%20Admin%20Toolkit%20Overview.pdf
