### ISSUE TITLE
Unexpected error when use the "Save" button on (Entra ID) Groups in FO

### ISSUE THREAD

**Issue by Dynamicspedia** [ameyer505/D365FOAdminToolkit#46]
It is noticed that the "Save" button in System Administration - Users - Groups does give an error message, when pressed twice or pressed when not necessary (because there were no changes or changes were saved automatically). The error message says "Cannot create a record in Entra ID group dynamic role assignment (ADMEntraIdGroupSecurityRoleAssignmentRule). Reference: xxx, System user. The record already exists.".
 
This does not affect the behavior of the tool or break anything (as far as the person who reported it to me tested). I also validated it and I'm able to reproduce the issue. Also no side effects. It is confusing and should be prevented. I will start working on this soon.

**Comment by FH-Inway** [comment]
Sorry, could not resist taking this for a spin in a [Github Workspace session](https://copilot-workspace.githubnext.com/ameyer505/D365FOAdminToolkit/issues/46?shareId=f3bfb2cb-c420-4e3d-857a-59b8b2f6f404). It did pretty good, but I had to modify the plan to tell it which class and method to modify. But the rest looks good at first glance. Haven't tested it yet, though :smile:

**Comment by FH-Inway** [comment]
Validated that the changes work. Although the Copilot changes would have worked as well, once I got into it, I could not resist playing around with some stuff (unit of work, friend packages, navigation methods). Should be good to go now.
