### ISSUE TITLE
ESC does not cancel process

### ISSUE THREAD

**Issue by TrustCompact** [ameyer505/D365FOAdminToolkit#7]
If logging is enabled and you press ESC in the process while system is asking for a reason for grant/revoke, process is executed anyway!

**Comment by ameyer505** [comment]
Thanks for pointing this out, this has been addressed in the v1.1 release

**Comment by headcase-fo** [comment]
@ameyer505 Unfortunately I could reproduce the same issue in the v1.3 release (running on 10.0.39.)

**Comment by jofme** [comment]
@headcase-fo I'll have a look at it

**Comment by jofme** [comment]
@headcase-fo Reproduced and fix submitted for merging
